name: warning_electronic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_analytics: ^10.10.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_database: ^10.4.3
  go_router: ^13.2.1
  provider: ^6.1.2
  google_sign_in: ^6.1.0
  flutter_riverpod: ^2.5.0
  firebase_messaging: ^14.7.18
  flutter_local_notifications: ^17.0.0
  audioplayers: ^5.2.1
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  permission_handler: ^11.3.0
  async: ^2.11.0
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/sounds/alarm.mp3
    - assets/icon/app_icon.png  # icon mới của bạn

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
