// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZI1_60nhkGFVZ_KCMLifKibvzWUfQL2w',
    appId: '1:994164164674:web:2da526add9807b5ba505db',
    messagingSenderId: '994164164674',
    projectId: 'power-failure-warning-device',
    authDomain: 'power-failure-warning-device.firebaseapp.com',
    databaseURL: 'https://power-failure-warning-device-default-rtdb.firebaseio.com',
    storageBucket: 'power-failure-warning-device.firebasestorage.app',
    measurementId: 'G-NV1N588BBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVPLNB_8Es28ORPPJHQfpMa8Kt-A8DInY',
    appId: '1:994164164674:android:dda00d64764702bea505db',
    messagingSenderId: '994164164674',
    projectId: 'power-failure-warning-device',
    databaseURL: 'https://power-failure-warning-device-default-rtdb.firebaseio.com',
    storageBucket: 'power-failure-warning-device.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzCkPdlCVQxYiPU4E6Jxhn7XOFNa8nxu8',
    appId: '1:994164164674:ios:cbc66e84318393f3a505db',
    messagingSenderId: '994164164674',
    projectId: 'power-failure-warning-device',
    databaseURL: 'https://power-failure-warning-device-default-rtdb.firebaseio.com',
    storageBucket: 'power-failure-warning-device.firebasestorage.app',
    iosClientId: '994164164674-bkpp66uebqaefe547384kum5rnggctcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appLostElectronicFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzCkPdlCVQxYiPU4E6Jxhn7XOFNa8nxu8',
    appId: '1:994164164674:ios:cbc66e84318393f3a505db',
    messagingSenderId: '994164164674',
    projectId: 'power-failure-warning-device',
    databaseURL: 'https://power-failure-warning-device-default-rtdb.firebaseio.com',
    storageBucket: 'power-failure-warning-device.firebasestorage.app',
    iosClientId: '994164164674-bkpp66uebqaefe547384kum5rnggctcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appLostElectronicFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZI1_60nhkGFVZ_KCMLifKibvzWUfQL2w',
    appId: '1:994164164674:web:e0c614e008870ceaa505db',
    messagingSenderId: '994164164674',
    projectId: 'power-failure-warning-device',
    authDomain: 'power-failure-warning-device.firebaseapp.com',
    databaseURL: 'https://power-failure-warning-device-default-rtdb.firebaseio.com',
    storageBucket: 'power-failure-warning-device.firebasestorage.app',
    measurementId: 'G-WDJM6XRF8Y',
  );

}